version: '3'
services:
  postgrest:
    build: 
      context: ./api
      args: 
        - POSTGREST_VERSION=v7.0.1
    environment:
      - POSTGRES_DB_HOST=db-blue
      - POSTGRES_DB=sirene
      - POSTGRES_USER=sirene
      - POSTGRES_PASSWORD=sirene
      - POSTGRES_DB_PORT=5432
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.postgrest.rule=Host(`localhost`)"
      - "traefik.http.routers.postgrest.entrypoints=postgrest"
      - "traefik.port=3000"
networks:
    traefik:
        external:
            name: backend-siren_backendsiren
