CREATE TABLE siret
(
	id_siret SERIAL PRIMARY KEY NOT NULL,
    siren CHARACTER VARYING,
    nic DECIMAL(9,2),
    siret CHARACTER VARYING,
    statutDiffusionEtablissement CHARACTER VARYING,
    dateCreationEtablissement date default NULL,
    trancheEffectifsEtablissement CHARACTER VARYING,
    anneeEffectifsEtablissement DECIMAL(9,2),
    activitePrincipaleRegistreMetiersEtablissement CHARACTER VARYING,
    dateDernierTraitementEtablissement TIMESTAMP default NULL,
    etablissementSiege BOOLEAN,
    nombrePeriodesEtablissement DECIMAL(9,2),
    complementAdresseEtablissement CHARACTER VARYING,
    numeroVoieEtablissement CHARACTER VARYING,
    indiceRepetitionEtablissement CHARACTER VARYING,
    typeVoieEtablissement CHARACTER VARYING,
    libelleVoieEtablissement CHARACTER VARYING,
    codePostalEtablissement DECIMAL(9,2),
    libelleCommuneEtablissement CHARACTER VARYING,
    libelleCommuneEtrangerEtablissement CHARACTER VARYING,
    distributionSpecialeEtablissement CHARACTER VARYING,
    codeCommuneEtablissement CHARACTER VARYING,
    codeCedexEtablissement CHARACTER VARYING,
    libelleCedexEtablissement CHARACTER VARYING,
    codePaysEtrangerEtablissement CHARACTER VARYING,
    libellePaysEtrangerEtablissement CHARACTER VARYING,
    complementAdresse2Etablissement CHARACTER VARYING,
    numeroVoie2Etablissement CHARACTER VARYING,
    indiceRepetition2Etablissement CHARACTER VARYING,
    typeVoie2Etablissement CHARACTER VARYING,
    libelleVoie2Etablissement CHARACTER VARYING,
    codePostal2Etablissement DECIMAL(9,2),
    libelleCommune2Etablissement CHARACTER VARYING,
    libelleCommuneEtranger2Etablissement CHARACTER VARYING,
    distributionSpeciale2Etablissement CHARACTER VARYING,
    codeCommune2Etablissement CHARACTER VARYING,
    codeCedex2Etablissement CHARACTER VARYING,
    libelleCedex2Etablissement CHARACTER VARYING,
    codePaysEtranger2Etablissement CHARACTER VARYING,
    libellePaysEtranger2Etablissement CHARACTER VARYING,
    dateDebut  date default NULL,
    etatAdministratifEtablissement CHARACTER VARYING,
    enseigne1Etablissement CHARACTER VARYING,
    enseigne2Etablissement CHARACTER VARYING,
    enseigne3Etablissement CHARACTER VARYING,
    denominationUsuelleEtablissement CHARACTER VARYING,
    activitePrincipaleEtablissement CHARACTER VARYING,
    nomenclatureActivitePrincipaleEtablissement CHARACTER VARYING,
    caractereEmployeurEtablissement CHARACTER VARYING,
    longitude  NUMERIC(14, 11),
    latitude  NUMERIC(14, 11),
    geo_score  DECIMAL(9,2),
    geo_type CHARACTER VARYING,
    geo_adresse CHARACTER VARYING,
    geo_id CHARACTER VARYING,
    geo_ligne CHARACTER VARYING, 
    geo_l4 CHARACTER VARYING,
    geo_l5 CHARACTER VARYING,
    typecom CHARACTER VARYING,
    reg CHARACTER VARYING,
    dep CHARACTER VARYING,
    arr CHARACTER VARYING,
    tncc CHARACTER VARYING, 
    ncc CHARACTER VARYING, 
    nccenr CHARACTER VARYING, 
    libelle CHARACTER VARYING, 
    can CHARACTER VARYING,
    comparent CHARACTER VARYING,
    CONSTRAINT fk_siren
        FOREIGN KEY(siren)
            REFERENCES siren(siren)
)
TABLESPACE pg_default;
